### ISSUE TITLE
AttestationReport not verifiable without openssl feature

### ISSUE THREAD

**Issue by fspreiss** [virtee/sev#109]
The `sev::firmware::guest::types::snp::AttestationReport` is currently not verifiable without the `openssl` feature.

On the one hand, this is because `impl sev::certs::snp::Verifiable for (&Chain, &AttestationReport)` is only available with the `openssl` feature. On the other hand, even if one would want to implement the verification logic manually (for example with the pure-Rust `p384` crate), this is not possible because in the report's `signature: sev::certs::snp::ecdsa::Signature`, both `r` and `s` are private fields.

Are there plans to provide the verification logic also in a pure Rust fashion, that is, without the `openssl` feature?

If not, a stop-gap solution could be to create public getters for `r` and `s`, so that at least a manual verification (e.g., with [p384](https://crates.io/crates/p384)) becomes possible. Alternatively, one could make the fields `pub`lic, given that the attestation report's `signature` field is also public. Yet another alternative would be to provide a pure-rust `to_der` method, which is effectively what the `openssl`-gated `impl TryFrom<&Signature> for Vec<u8>` currently does.

In our project, we'd like to move away from OpenSSL so that all our code is in (safe) Rust. One of the last blockers in this regard is the verification of the attestation report, so it would be great if we could find a solution here.

In general, would you be open to contributions/PRs, e.g., for implementing the mentioned public getters for `r` and `s`?

**Comment by larrydewey** [comment]
Closing, as your PR was merged :slightly_smiling_face:

**Comment by fspreiss** [comment]
> Closing, as your PR was merged

@larrydewey, sure! Very happy to see the PR(s) merged!

Do you maybe have a rough estimate on when a new release would be cut that contains #111 (and #112)? This info would help us with our internal planning. Thanks.
