### ISSUE TITLE
SEV-ES attestation

### ISSUE THREAD

**Issue by pegahnikbakht** [virtee/sev#116]
Hi,

Can some one help me to figure out how to get attestation report from a SEV-ES VM? 

Thanks in advance for the help.

**Comment by tylerfanelli** [comment]
Hi @pegahnikbakht, when you mention "_from a SEV-ES VM_" are you referring to **within** the guest? If so, that is only available with SEV-SNP. SEV and SEV-ES both follow a pre-attestation model, where the attestation is handled by the host.
