### ISSUE TITLE
Panic when getting an extended report

### ISSUE THREAD

**Issue by heavenboy8** [virtee/sev#122]
Hi,

I'm using the `sev` crate on an SEV-SNP VM provided by GCP (private preview). I want to generate an extended report using `pub fn get_ext_report([...])`. The code panics with that error : 

```
[...] panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0xffffffffffffffff', /home/user/sev/src/firmware/linux/host/types/snp.rs:183:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
Aborted
```

The line 183 is `entry = *data;` from `parse_table` function called in the `get_ext_report` function. The value of `ext_report_request.certs_address` is equal to `u64::MAX` as it has been initialized by the constructor `pub fn new(data: &ReportReq)`. 

My thought is that on this machine no certificate has been cached by GCP and therefore no certificate was returned by the `ioctl`. The value of `ext_report_request.certs_len` is equal to zero before entering into the `unsafe` parsing instruction. 

I would like therefore to suggest a fix. Before parsing the `CertTableEntry`, check if the `ext_report_request.certs_len` is equal to zero. If so, we have 2 options:
- Return an `Err(CertError::EmptyCertBuffer)`
- Return an empty `Vec<CertTableEntry>`

As a user of the API, I guess the second option is better. If no certificate is configured, just return an empty `vec`. If we raise an error, I must implement an error handler which will call the non extend report  function whereas the report has already been generated by this previous function call. 

What do you think ?

**Comment by heavenboy8** [comment]
@tylerfanelli any idea in mind concerning the issue I have reported?

Thanks again for the great job on this project.

**Comment by tylerfanelli** [comment]
@heavenboy8 Sorry, just seeing this. I think option 2 would be best. Like you said, since there are no certs, just return an empty `Vec<CertTableEntry>`, or we could return an `Option<Vec<CertTableEntry>>` and return `None` with empty cert buffer.

**Comment by tylerfanelli** [comment]
@heavenboy8 thanks!

**Comment by larrydewey** [comment]
I am not sure I agree with @tylerfanelli  here. If you are calling for and extended request, but no certificates are loaded, I would think returning an error would make more sense, as we can specify more clearly that the certificate chain was not provided by the host. If we want to retrieve a standard attestation report, we should use:

[get_report(..)](https://github.com/virtee/sev/blob/d16e8f227c089fb9ce22a0e660790f1980fed49b/src/firmware/guest/mod.rs#L96C17-L96C17)

**Comment by tylerfanelli** [comment]
@larrydewey I think we should only return an error when the `SNP_GET_EXT_REPORT` `ioctl` fails. If we return an error on `get_ext_report()`, then you may wonder if something is wrong with your inputs or system that caused the `ioctl` itself to fail. In reality, this is not the case. Everything worked completely fine, there just wasn't any certificates loaded for you to fetch.

**Comment by tylerfanelli** [comment]
@larrydewey An `Option<CertTableEntry>` return value of `None` would be the system's way of telling you that no certs are loaded.
