### ISSUE TITLE
AWS and Azure

### ISSUE THREAD

**Issue by pegahnikbakht** [virtee/sev#132]
Hi, 

Does snpguest support attestation generation on Azure and AWS sev-snp? 

Regards,
Pegah

**Comment by tylerfanelli** [comment]
@pegahnikbakht It may be better to ask this question under the snpguest repository. This repo is for the sev library. Regardless, there is restricted (i.e. not full) support for Azure under snpguest. AFAIK AWS doesn't do anything special for the SEV-SNP guest environment, so I would say yes although I haven't personally tried the tool on it.
