### ISSUE TITLE
Inconsistency in guest policy structs used for attestation and id block

### ISSUE THREAD

**Issue by its-luca** [virtee/sev#165]
There seem to be at least two structs [2] and [3] that model the guest policy defined in Table 9 in [1]. However the definition in [3] only defines a subset of the features defined in [2]. 

Besides this discrepancy, the fact that there are two structs for the guest policy is quite confusing, as [3] is used when generating the ID block and [3] is used for the attestation report. Thus when writing software to start a SEV VM and do attestation we need to input the same information in two different formats/structs. It would seem more natural to me to use one definition.

If you agree with this assessment, I could look into refactoring the code accordingly.

[1] https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf
[2] https://github.com/virtee/sev/blob/0e15b313691ea32029e579fa59a4e9d399fd0a1d/src/firmware/guest/types/snp.rs#L420
[3] https://github.com/virtee/sev/blob/0e15b313691ea32029e579fa59a4e9d399fd0a1d/src/launch/snp.rs#L129

**Comment by larrydewey** [comment]
@its-luca This is definitely a duplication of code. In my opinion, it would make the most sense to import the definition from `sev/src/firmware/guest/types/snp.rs` into `sev/src/launch/snp.rs`. @tylerfanelli do you have any opinion about this?

**Comment by tylerfanelli** [comment]
Importing the definition makes the most sense, I would agree.
