### ISSUE TITLE
Randomness Generation - Guarantee its from SEV Enclave. 

### ISSUE THREAD

**Issue by Astewart1510** [virtee/sev#189]
Hi there,

I am migrating from Intel SGX with Gramine, where we can request randomness securely sourced from the enclave. I am trying to find a similar feature in AMD SEV.

I noticed that the sev crate uses OpenSSL to generate randomness, which likely leverages the system's RNG. However, does this method guarantee that the randomness is sourced specifically from the SEV enclave?

Could you provide advice or technical guidance on how to generate randomness securely within the SEV enclave?

Thank you!

**Comment by larrydewey** [comment]
For clarification @Astewart1510, are you using SEV/SEV-ES or are you using SEV-SNP?

**Comment by larrydewey** [comment]
> I noticed that the sev crate uses OpenSSL to generate randomness, which likely leverages the system's RNG. However, does this method guarantee that the randomness is sourced specifically from the SEV enclave?

No. Unfortunately using the openssl RNG does not guarantee all randomness generated by `/dev/urandom` (what seeds the RNG for OpenSSL) originated from the enclave itself. The Linux kernel will add sources of randomness, potentially from the VMM/Hypervisor, to be mixed into the random sources. While it is likely to be okay, it does not guarantee a singular origin.

> Could you provide advice or technical guidance on how to generate randomness securely within the SEV enclave?

One of the best sources for randomness would be calling the x86 instruction `RDRAND`, as all CPU instructions are protected by the Guest Hypervisor Communication Block (GHCB), and may be considered trusted. The CPU instruction will generate randomness from the AMD Secure Processor SOC.

**Comment by Astewart1510** [comment]
Thank you! apologies for my delayed response here.
