### ISSUE TITLE
Instantiating FamilyId and ImageId types

### ISSUE THREAD

**Issue by its-luca** [virtee/sev#192]
Hi everyone,

I am using this library to write some tooling for attesting SEV-SNP VMs.
I want to implement support for the early ID-block attestation but I am currently running into some problems with the  type definitions for this library.
I don't see any way to instantiate the FamilyId https://github.com/virtee/sev/blob/4ea2d2c32a9fe13c0c3eea6df674876d2f0d471d/src/measurement/idblock_types.rs#L75  type. The test case https://github.com/virtee/sev/blob/4ea2d2c32a9fe13c0c3eea6df674876d2f0d471d/tests/id-block.rs#L36-L44 does not use this field. I guess I could use Deserialize implementation as a workaround but that seems a bit hacky.
Would you be fine with adding a constructor from e.g. [u8] to this type? In addtion`std::cmp::Eq` would be convenient, so that we can check can verify the FamilyId from the attestation report later on.
The ImageId type has the same issue.
I could create a corresponding pull request.

Cheers,
its-luca

**Comment by DGonzalezVillal** [comment]
Addressed in https://github.com/virtee/sev/pull/196

**Comment by larrydewey** [comment]
Should be resolved. @its-luca can you tests off `main` to see if this resolves this?

**Comment by tylerfanelli** [comment]
ping -- @its-luca Is this issue resolved?

**Comment by its-luca** [comment]
Yes. Thank you for your efforts and patience.
