### ISSUE TITLE
new OVMF changes break the measurement computation

### ISSUE THREAD

**Issue by gianlucascopelliti** [virtee/sev#194]
It looks like recent versions of the `AMDESE/ovmf` repository made some changes to the SEV metadata section in the OVMF binary.

From what I could see in my tests, there seems to be a new `SectionType` with ID 4 (maybe related to the SVSM?) that the library does not support yet. Indeed, I'm getting errors on the function `OvmfSevMetadataSectionDesc::try_from_bytes` called by `parse_sev_metadata`, both functions defined in `src/measurement/ovmf.rs`.

I'm not entirely sure, but it should be about some commits made on April 17 (between https://github.com/AMDESE/ovmf/commit/c212fec9cf086243a7fb01cea185e67c2bd8f72e and https://github.com/AMDESE/ovmf/commit/0afb8743493853e30171f6000de51242e22a1eb8), since if I remove those commits everything works fine.

Let me know if you can reproduce the issue, I can provide more details if needed.

**Comment by larrydewey** [comment]
@DGonzalezVillal is working on a PR right now to fix this behavior.

**Comment by DGonzalezVillal** [comment]
Addressed in https://github.com/virtee/sev/pull/196

**Comment by tylerfanelli** [comment]
@gianlucascopelliti #196 was merged. Can you test?

**Comment by gianlu33** [comment]
Yes, I confirm that the problem is solved now. Thanks!

**Comment by gianlucascopelliti** [comment]
Yes, I confirm that the problem is solved now. Thanks!
