### ISSUE TITLE
Unable to use `panic = "abort"` when using the library

### ISSUE THREAD

**Issue by jakubDoka** [virtee/sev#245]
Hello,

I was trying to reduce my application's binary size, which depends on this library. I am unable to use `panic = "abort` in my release profile because the library [declares](https://github.com/virtee/sev/blob/main/Cargo.toml#L34):
```
crate-type = ["staticlib", "dylib", "rlib"]
```
The compilation error:
```
error: the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`

error: could not compile `sev` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```
If I clone and remove the mentioned configuration, I can compile it.

I would like to know why the crate has this configuration and whether it could be removed or optionally disabled. My application is not using unwinding and it would save 500kb (9%)

**Comment by tylerfanelli** [comment]
The extra crate types are for using this library with a C API. https://github.com/virtee/sev?tab=readme-ov-file#using-the-c-api

How are you linking this crate?

**Comment by jakubDoka** [comment]
I just import it in Cargo.toml as a crate dependency, the app it self is a rust binary

**Comment by tylerfanelli** [comment]
It was for usage of this library in qemu. It was ultimately rejected.

**Comment by tylerfanelli** [comment]
I've removed this along with the rest of the C library. This should be fixed now.
