### ISSUE TITLE
Update to version 1.0.0

### ISSUE THREAD

**Issue by tylerfanelli** [virtee/sev#27]
cc @slp @crobinso 

We mentioned how getting to 1.0.0 would help some issues with cargo packaging. Once we can get all remaining open PRs merged (notably, SNP host/guest patches), I'll take the liberty to go to 1.0.0.

**Comment by slp** [comment]
Sounds good to me.

**Comment by larrydewey** [comment]
I just put up the last part of the SNP Host patches #32 Let me know if I can help out with the 1.0.0 release!

**Comment by tylerfanelli** [comment]
Closed by #38
