### ISSUE TITLE
Update Certificate Support for Genoa Systems

### ISSUE THREAD

**Issue by larrydewey** [virtee/sev#29]
Currently there are no certificates included for Genoa Systems. These will need to be added to support validation and attestation of that platform.

**Comment by tylerfanelli** [comment]
@larrydewey Is there any news on this?

**Comment by larrydewey** [comment]
@tylerfanelli we have the code together which worked for 0.3.0, but we are now seeing some odd behavior with sevctl and debugging it. I will let you know what we find.

**Comment by larrydewey** [comment]
We were able to isolate the issue we were having to an invalid certificate. The contents have been appropriately update, tested, and the export command (which was failing) is working as expected.

**Comment by tylerfanelli** [comment]
@larrydewey Closing this, as Genoa certificate support was addressed in #50
