### ISSUE TITLE
Separate subcrate "snp"

### ISSUE THREAD

**Issue by tylerfanelli** [virtee/sev#33]
I've heard of interest between Enarx/Profian for a separate subcrate within this crate for all SNP-related data/code. I would assume this would be mostly utilizing the [snp](https://github.com/enarx/snp) crate and importing that crate in this library. Do I have this right, and can I get some more details of Enarx/Profian's plan here? I'm willing to work with others, just looking for some more clarity.

@larrydewey @npmccallum

**Comment by tylerfanelli** [comment]
What would the policy be on crate ownership? I'd like to have commit/maintainer privileges on the github repo if possible.

**Comment by npmccallum** [comment]
That's not a problem.

**Comment by jepio** [comment]
So I think from a code management point of view it would be easier to keep two crates inside the same repository, but in different subdirectories. I don't know if rust has a problem with that layout, but that feels like the right layout, which would allow people to import snp without the rest of sev.

**Comment by jepio** [comment]
Or to put things differently: in my opinion less-but-bigger repositories are easier to handle than more-but-smaller repositories.

**Comment by tylerfanelli** [comment]
@jepio Yea, that's the way we're trying to go with this. Allowing others to just use the `snp` crate and ignore the rest of the legacy SEV is a goal.

See the [initial PR for the snp repo](https://github.com/virtee/snp/pull/1)

**Comment by tylerfanelli** [comment]
@jepio Closing this. With our latest PR #74, you can now just use the SEV-SNP portion of the library by specifying this in a `Cargo.toml`:

`sev = { version = $VERSION, default-features = false, features = [ "snp" ] }`
