### ISSUE TITLE
Add helper methods to the SnpExtReportReq type

### ISSUE THREAD

**Issue by larrydewey** [virtee/sev#43]
In hind-sight it would have been really good to add in some helper methods to get a more Rust friendly access to the data located at the pointers returned from the kernel here. I will create a PR to add some of this functionality in.

- [x] A obtain a copy of the certificates once the snp_get_ext_report() call had been completed (vector of CertTableEntry, etc).

**Comment by dubek** [comment]
Another way to look at this: can we provide a rust-friendly `snp_get_ext_report()`, something like:

```
fn snp_get_ext_report(report_data: [u8; 64]) -> (AttestationReport, Certs)
```

It would automatically allocate a buffer for the certificates (maybe ioctl once with 0 to get the expected length and then ioctl again after allocating enough room). I basically want to hide all the low-level C stuff (pointers, buffer lengths).

Another thing to consider: in some places (for example, confidential containers KBC), the guest fetches the attestation report and certs but doesn't parse them; it just passes them as opaque buffers to the attestation-server/verifier (which then needs to parse them). In that usage it makes sense to have a version that just returns `Vec<u8>`s (or make the AttestationReport and CertTableEntry serializable back to bytes, but that feels like "double work").

(@fitzthum FYI)

**Comment by fitzthum** [comment]
Yeah I think that signature is exactly what we want. Might add a VMPL level as input. It would be nice to avoid having to make a nested report request and extended report request.

**Comment by fitzthum** [comment]
My impression is that certificate parsing will usually be handled remotely by the verifier. The guest really just needs to send the certs off somewhere else. So probably we should just return certs as a `Vec<u8>`.

**Comment by tylerfanelli** [comment]
@fitzthum I see, so hiding away the low-level C stuff (pointers, buffer lengths) would only be done for the regular `snp_get_ext_report()` returning `(AttestationReport, Certs)`. Not for an API returning `(Vec<u8>, Vec<u8>)`.

**Comment by fitzthum** [comment]
We want to hide the pointers no matter what. I'm just saying that we probably don't need to worry about parsing the certs. Currently we get the certs by making an extended report request and then unsafely copying from the provided buffer (with length). Instead it would be nice to just get a Vec<u8> with the same data and never have to touch the pointer.

**Comment by larrydewey** [comment]
@fitzthum I agree, hiding the pointers is definitely important. I just missed this last part in my former PR. I decided to change the return type to:

```rust
-> Result<(AttestationReport, CertTable), Indeterminate<Error>> {
```

Which should resolve your concern. I also added serialization support for all of the associated data types with serde, so you should be able to use `serde_json` to serialize it for the CC service.

**Comment by dubek** [comment]
Note that the attestation report is 0x4a0 bytes long.
The first 0x2a0 bytes are data fields.
The rest (0x200 bytes) are the signature, which is: "Signature of bytes 0h to 29Fh inclusive of this report. The format of the signature is described inChapter 10."

So the verifier must be able to construct the first 0x2a0 bytes of the data fields exactly as produced by the PSP.

If we serialize each field to JSON, we must be sure that when we deserialize back into a struct we can produce the exact 0x2a0 bytes that we started from.

**Comment by larrydewey** [comment]
@dubek Correct. I am not sure there is much more that we can do than instruct LLVM that the structure must follow legacy C format with `#[repr(C)]`.

Marshaling data is definitely tricky. So I am open to any suggestions here, but once the data has been serialized it is up to serde_json to make sure things follow the proper format.

**Comment by dubek** [comment]
Maybe we can just return a `[u8; 0x4a0]` slice, or encapsulate that in a simple UnverifiedAttestationReport type.

And then after you verify the signature convert it to an AttestationReport with all the nice fields in it.

(I haven't thought about this all the way through.)
