### ISSUE TITLE
Breaking API change with PlatformStatusFlags

### ISSUE THREAD

**Issue by Fuzzy-Math** [virtee/sev#57]
Commit #0cf2415 removes a public export of PlatformStatusFlags which is a breaking api change. Affects any dependents building against version 1.1.0

**Comment by larrydewey** [comment]
@Fuzzy-Math can you verify your import path? The import path should be:

```rust
use sev::firmware::host::types::PlatformStatusFlags
```

**Comment by Fuzzy-Math** [comment]
@larrydewey @tylerfanelli, Of course for sevctl, [#0d11e10](https://github.com/virtee/sevctl/commit/0d11e1080b14ae5957425c2673236f92c7c2b646) fixes the breakage when updating to `sev 1.1.0`. But the underlying issue is that #0cf2415 was a [breaking API change](https://doc.rust-lang.org/cargo/reference/semver.html#item-remove) and removing the public export should have never happened to begin with. I was just trying to do the "correct" fix, but I guess I wasn't quick enough :)

Practically speaking, this did break a downstream build while packaging sevctl, so I thought I would do my part of hopefully reducing confusion with Rust semver compatibility.

**Comment by tylerfanelli** [comment]
@Fuzzy-Math Yea, breaking API with that change shouldn't have happened to begin with. Apologies for the confusion. Thanks for bringing this to our attention.
