### ISSUE TITLE
Change in Kernel User-space Behavior 

### ISSUE THREAD

**Issue by larrydewey** [virtee/sev#63]
The kernel patch by pgonda@google.com in kernel hash 47894e0f changed the ioctl return for SNP_GET_EXT_REPORT to succeed instead of returning an error when encountering an invalid certificate length. This was done to keep the cryptography safe. Because of this, any kernel before this hash (5.19, etc) behaves significantly differently, and we need to patch the way the API handles the error response.

**Comment by tylerfanelli** [comment]
@larrydewey Can you link the commit with breakage?

**Comment by larrydewey** [comment]
Hey @tylerfanelli I wasn't sure which link you were looking for:

[LKML Discussion and PR](https://lore.kernel.org/all/20221116175558.2373112-1-pgonda@google.com/)
[Github Context](https://github.com/torvalds/linux/commit/033e84da29cdee96cc2649504f05da5aace4b2df)
