### ISSUE TITLE
Update crates.io

### ISSUE THREAD

**Issue by fitzthum** [virtee/sev#7]
I notice that [crates.io](https://crates.io/crates/sev) still points to the old repository. Is there a plan to update this?

It looks like the issue with `Policy::From<u32>` has been fixed, but I don't think that is in any release. Are any future releases planned?

**Comment by slp** [comment]
Hi Tobin. Yes, the idea is to keep maintaining this crate and publishing new releases. @tylerfanelli may be able to give you some info about the timeline.

**Comment by tylerfanelli** [comment]
@fitzthum Hi. I'm looking to have a new release of the crate within the next couple weeks. There's been numerous issues closed and features added since the last release, so I'd like a new release ASAP. I'll link this issue once a new release is on crates.io

**Comment by fitzthum** [comment]
Great. Thanks @slp and @tylerfanelli

**Comment by tylerfanelli** [comment]
@fitzthum Apologies for the delay. Just would like to let you know we have a new release on crates.io
