### ISSUE TITLE
breaking API changes in v1.2.0

### ISSUE THREAD

**Issue by decathorpe** [virtee/sev#93]
Some commits between v1.1.0 and v1.2.0 broke the public API of this crate. From what I can tell, these are the commits that introduced breaking changes:

- https://github.com/virtee/sev/commit/44361e394c05bf2443b64e98f62c40c103f8965b: broke public import paths
- https://github.com/virtee/sev/commit/e661ee291d0c8474b3e8928b04913702a81b24ce: broke public import paths
- https://github.com/virtee/sev/commit/51760d6e7d665bb9e00d2f459d6c45a28063384d: changed names and arguments of public functions

All three changes are breaking API changes, so 1.2.0 should definitely have been released as 2.0.0 instead. The current version breaks SemVer API stability promises, and breaks builds of dependent projects.

For example, running `cargo install sevctl` fails since v1.2.0 of the "sev" crate was published.

---

For a good way to see the differences in public API between v1.1.0 and v1.2.0, you can look at the automatically generated docs.

For the first commit that changed import paths in the `certs` module:

- https://docs.rs/sev/1.1.0/sev/certs/index.html
- https://docs.rs/sev/1.2.0/sev/certs/index.html

For the second commit that changed things in the `firmware` module:

- https://docs.rs/sev/1.1.0/sev/firmware/guest/index.html
- https://docs.rs/sev/1.2.0/sev/firmware/guest/index.html

For the third commit that changed argument types in a function that's part of the public API:

- https://docs.rs/sev/1.1.0/sev/firmware/guest/struct.Firmware.html#method.snp_get_report
- https://docs.rs/sev/1.2.0/sev/firmware/guest/struct.Firmware.html#method.get_report

---

c.f. https://bugzilla.redhat.com/show_bug.cgi?id=2221017#c1

**Comment by larrydewey** [comment]
From what @tylerfanelli was telling me, I believe this has been resolved? If you have additional questions, feel free to re-open this.

**Comment by tylerfanelli** [comment]
Not exactly "fixed" yet, but we're working around it in Fedora with w/r/t libkrun and sevctl.

**Comment by decathorpe** [comment]
The only "real" way to fix the problem would be to re-release 1.2.0 as 2.0.0, but working around the API breaks in dependent projects is the next best thing, I guess.
