### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pegahnikbakht** [virtee/sev#95]
Hello, 
Does Virtee has any documentation on how to use it?

**Comment by larrydewey** [comment]
Hi @pegahnikbakht here are some good resources:

[SEV Documentation](https://docs.rs/sev/1.2.1/sev/)
[SEV User Guide](https://www.amd.com/content/dam/amd/en/documents/developer/58217-epyc-9004-ug-platform-attestation-using-virtee-snp.pdf)

Let me know if you have any specific questions
